version: "3.4"
networks:
  common_net:
    name: common_net
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "1Secure*Password1"
        MSSQL_PID: Express
    ports:
        - "1401:1433"
    networks:
        - common_net
  web-api:
    build: .
    depends_on:
        - sqlserver
    ports:
        - "8080:80"
    networks:
        - common_net